# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 冯雨嘉的个人网页
zh-Hant:
    languageCode: zh-Hant
    contentDir: content/zh-Hant
    title: 冯雨嘉的人W
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 
#        url: '#about'
#        weight: 1
